### ISSUE TITLE
Issue when using the command /id price reason

### ISSUE THREAD

**Issue by imbader** [Mojito-Fivem/qb-billing#1]
Client.lua 20 attempt concatante nil value (local'price')

**Comment by imbader** [comment]
Fixed the client.lua and replaced the line with the following:


 message = "You have been sent a bill for, <br>Amount: <br> $"..price," for "..reason,"<br><br> press the button below to accept the bill",

**Comment by imbader** [comment]
Issue was ..price.. 
changed to 
..price,

**Comment by Mojito-Fivem** [comment]
This is working, submit a pull request if you think something isn't working as intended.
