### ISSUE TITLE
Adding function

### ISSUE THREAD

**Issue by Spydermonk** [Mojito-Fivem/qb-billing#2]
Add true/false statement where true sends to society account false sends it to player who sent bill. Added the following. Also when using base version it doesnt pull the names correctly. it will popup system msg you sent a a bill to yourname for amount reason

Here is the snippets of what i added but cannot get working. Will not deduct from player's bank or cash when set to true but if flag is set to false it works.

`QBCore.Commands.Add("createbill", "Bill Player", {{name="true/false", help="Type true if its company bill"}, {name="id", help="Player ID"}, {name="amount", help="Fine Amount"}, {name="reason", help="Reason of the bill"}}, false, function(source, args)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    local OtherPlayer = QBCore.Functions.GetPlayer(tonumber(args[2]))
    
    if OtherPlayer ~= nil then
        name = Player.PlayerData.charinfo.firstname.." "..Player.PlayerData.charinfo.lastname
        citizenid = OtherPlayer.PlayerData.citizenid
        OtherPlayer = OtherPlayer.PlayerData.charinfo.firstname.." "..OtherPlayer.PlayerData.charinfo.lastname
        job = Player.PlayerData.job
        companybill = tostring(args[1])
        playerId = tonumber(args[2])
        price = tonumber(args[3])

        table.remove(args, 1)
        table.remove(args, 1)
        table.remove(args, 1)
        local reason = table.concat(args, " ")

        if price and price > 0 then
            if companybill == "true" then
                TriggerClientEvent("qb-billing:sendbill", playerId, name, price, reason, citizenid, job)
                TriggerClientEvent('chatMessage', src, "SYSTEM", "inform", "You sent companybill to ".. OtherPlayer .." with ".. price .."$ for ".. reason ..".")

                QBCore.Functions.ExecuteSql(false, "INSERT INTO `phone_invoices` (`citizenid`, `amount`, `society`, `title`) VALUES ('" .. citizenid .. "', " .. price .. ", '" .. Player.PlayerData.job.name .. "', '" .. reason .. "')", function()
                    TriggerClientEvent("qb-phone:RefreshPhone", OtherPlayer.PlayerData.source)
                end)
            else
                TriggerClientEvent("qb-billing:sendbill", playerId, name, price, reason, citizenid)
                TriggerClientEvent('chatMessage', src, "SYSTEM", "inform", "You sent bill to ".. OtherPlayer .." with ".. price .."$ for ".. reason ..".")
            end
        else
            TriggerClientEvent('chatMessage', src, "SYSTEM", "error", "Invalid amount.")
        end
    else
        TriggerClientEvent('chatMessage', src, "SYSTEM", "error", "Invalid Player ID!")
    end
end)

RegisterNetEvent('qb-billing:paybill')
AddEventHandler('qb-billing:paybill',function(data)
    local Player = QBCore.Functions.GetPlayer(source)
    local OtherPlayer = QBCore.Functions.GetPlayerByCitizenId(data[2])
    local bank = Player.PlayerData.money.bank
    local cash = Player.PlayerData.money.cash
    local name = Player.PlayerData.charinfo.firstname.." "..Player.PlayerData.charinfo.lastname
    local rsender = ""
    local checkmsg = ""
    
    if Player ~= nil then
        if cash >= data[1] or bank >= data[1] then
            if bank >= data[1] then
                Player.Functions.RemoveMoney("bank", data[1], "paid-bill")
            else 
                Player.Functions.RemoveMoney("cash", data[1], "paid-bill")
            end

            if OtherPlayer ~= nil then
                if data[5] ~= nil then
                    rsender = data[5].label
                    checkmsg = "Payment was sent to ".. data[5].label .." society account."
                    TriggerEvent("qb-society:bossmenu:server:addAccountMoney", data[5].name , data[1])
                else
                    rsender = name
                    checkmsg = "Payment was sent to your bank account."
                    OtherPlayer.Functions.AddMoney("bank", data[1], "recieved-bill")
                end

                TriggerEvent('qb-phone:server:sendNewMailToOffline', OtherPlayer.PlayerData.citizenid, {
                    sender = "".. name .."",
                    subject = "Bill payment",
                    message = "Payment for the invoice was sent,<br>Sender name: "..Player.PlayerData.charinfo.firstname.. " ".. Player.PlayerData.charinfo.lastname .." <br>Amount: ".. data[1] .."$<br>Reason: ".. data[3] ..".<br><br>".. checkmsg .."",
                })
            end
        else
            -- if he got no money
        end
    end
end)
RegisterNetEvent('qb-billing:paybill')
AddEventHandler('qb-billing:paybill',function(data)
    local Player = QBCore.Functions.GetPlayer(source)
    local OtherPlayer = QBCore.Functions.GetPlayerByCitizenId(data[2])
    local bank = Player.PlayerData.money.bank
    local cash = Player.PlayerData.money.cash
    local name = Player.PlayerData.charinfo.firstname.." "..Player.PlayerData.charinfo.lastname
    local rsender = ""
    local checkmsg = ""
    
    if Player ~= nil then
        if cash >= data[1] or bank >= data[1] then
            if bank >= data[1] then
                Player.Functions.RemoveMoney("bank", data[1], "paid-bill")
            else 
                Player.Functions.RemoveMoney("cash", data[1], "paid-bill")
            end

            if OtherPlayer ~= nil then
                if data[5] ~= nil then
                    rsender = data[5].label
                    checkmsg = "Payment was sent to ".. data[5].label .." society account."
                    TriggerEvent("qb-society:bossmenu:server:addAccountMoney", data[5].name , data[1])
                else
                    rsender = name
                    checkmsg = "Payment was sent to your bank account."
                    OtherPlayer.Functions.AddMoney("bank", data[1], "recieved-bill")
                end

                TriggerEvent('qb-phone:server:sendNewMailToOffline', OtherPlayer.PlayerData.citizenid, {
                    sender = "".. name .."",
                    subject = "Bill payment",
                    message = "Payment for the invoice was sent,<br>Sender name: "..Player.PlayerData.charinfo.firstname.. " ".. Player.PlayerData.charinfo.lastname .." <br>Amount: ".. data[1] .."$<br>Reason: ".. data[3] ..".<br><br>".. checkmsg .."",
                })
            end
        else
            -- if he got no money
        end
    end
end)
`

**Comment by Mojito-Fivem** [comment]
1. Formating... 2. Is this a feauture request or what? and if so make a PR and I'll consider but I don't have any intention of adding to this resource myself.

**Comment by Spydermonk** [comment]
I'll turn into a pull req
